### ISSUE TITLE
[BUG] query with small clob as result is extremly slow (>4s) when not cast to smaller clob type

### ISSUE THREAD

**Issue by rfx77** [markdirish/node-odbc#141] opened 2020-11-24 11:34 UTC
hi!

when connecting to a db2 (ibm i, as400) database via odbc i see this problem:

i do a query which returens a clob: 
`select json_object('name' value 'test') as res from sysibm.sysdummy1`

the result type of this query is clob(2g) so the maximum size would be 2 gig. in reality the size is only 15 characters.
when i execute this query it takes about 5 seconds!!! (5000ms)

when i change the query to: 
`select cast(json_object('name' value 'test') as clob(32k)) as res from sysibm.sysdummy1`
the query runs in 25ms

this effect can only be seen when i use the odbc driver with node-odbc. no other development environment (delphi,...) has this problem with odbc. jdbc also works as expected.

the difference between the two querys is that the first one returns a differen type: clob(2g). the second returns clob(32k). in both situations there is no huge nettwork traffic so the driver definitely is NOT transferring more data.

Here is the complete code of my example:

```

var as400db = require('odbc');
var connstr = "DSN=XXXXXXX;UID=XXXXXXX;PWD=XXXXXXX";

var qry1 = "select cast(json_object('name' value 'test') as clob(32k)) as res from sysibm.sysdummy1"
var qry2 = "select json_object('name' value 'test') as res from sysibm.sysdummy1"

async function test() {
    console.log("connect")
    var conn = await as400db.connect(connstr)

    //warmup to be shure there is no sideffect
    await conn.query(qry1)
    await conn.query(qry2)

    console.log('--------------------------')
    var tm = Date.now()
    res  = await conn.query(qry1)
    console.log("time 1: " + (Date.now() - tm))
    console.log(res.columns)

    console.log('--------------------------')
    tm = Date.now()
    res  = await conn.query(qry2)
    console.log("time 2: " + (Date.now() - tm))

    console.log(res.columns)
}

test()

```

**Comment by rfx77** [comment] 2020-11-24 12:33
and there are timings of the same query with varying result types:

```
select cast(json_object('name' value 'test') as clob(32k)) as res from sysibm.sysdummy1      time: 65
select cast(json_object('name' value 'test') as clob(64k)) as res from sysibm.sysdummy1      time: 58
select cast(json_object('name' value 'test') as clob(128k)) as res from sysibm.sysdummy1     time: 59
select cast(json_object('name' value 'test') as clob(256k)) as res from sysibm.sysdummy1     time: 60
select cast(json_object('name' value 'test') as clob(512k)) as res from sysibm.sysdummy1     time: 57
select cast(json_object('name' value 'test') as clob(1024k)) as res from sysibm.sysdummy1    time: 61
select cast(json_object('name' value 'test') as clob(16384k)) as res from sysibm.sysdummy1   time: 122
select cast(json_object('name' value 'test') as clob(131072k)) as res from sysibm.sysdummy1  time: 418
select cast(json_object('name' value 'test') as clob(262144k)) as res from sysibm.sysdummy1  time: 783
select cast(json_object('name' value 'test') as clob(524288k)) as res from sysibm.sysdummy1  time: 1518
select cast(json_object('name' value 'test') as clob(1048576k)) as res from sysibm.sysdummy1 time: 2891



```

**Comment by rfx77** [comment] 2020-11-24 12:35
Or without the whole json_object thing:
```

select cast('test' as clob(32k)) as res from sysibm.sysdummy1      time: 67
select cast('test' as clob(64k)) as res from sysibm.sysdummy1      time: 63
select cast('test' as clob(128k)) as res from sysibm.sysdummy1     time: 65
select cast('test' as clob(256k)) as res from sysibm.sysdummy1     time: 81
select cast('test' as clob(512k)) as res from sysibm.sysdummy1     time: 67
select cast('test' as clob(1024k)) as res from sysibm.sysdummy1    time: 54
select cast('test' as clob(16384k)) as res from sysibm.sysdummy1   time: 101
select cast('test' as clob(131072k)) as res from sysibm.sysdummy1  time: 427
select cast('test' as clob(262144k)) as res from sysibm.sysdummy1  time: 795
select cast('test' as clob(524288k)) as res from sysibm.sysdummy1  time: 1519
select cast('test' as clob(1048576k)) as res from sysibm.sysdummy1 time: 2949
```

**Comment by rfx77** [comment] 2020-11-24 12:37
And this arer the results when executed over jdbc all runtimes are the ca same:

![image](https://user-images.githubusercontent.com/61699304/100094997-26ee0700-2e5a-11eb-9f11-bfe4c561d031.png)

**Comment by markdirish** [comment] 2021-02-12 16:39
@rfx77 , Sorry for getting to this so late. Looking into it now. I _THINK_ I know what the issue is and hopefully it is a quick fix.

**Comment by markdirish** [comment] 2021-02-16 15:56
I have identified the issue:

CLOB translates to the ODBC type of `SQL_LONGVARCHAR`, and it returns a column size of 2147483647. The current logic creates buffers of each column size, and in this case creates the 2GB buffer. Then when it gets the data, it is actually incredibly small.

What I am doing now instead is to take `SQL_LONGVARCHAR`, `SQL_WLONGVARCHAR`, and `SQL_LONGVARBINARY` columns and *don't* bind them with a buffer, but use `SQLGetData` to get the data piecemeal. We can create a smaller buffer this way, and transfer data in smaller chunks, which will greatly speed up for small CLOBs like this.

In fact, I have this implemented (very crudely) and it is returning my results in 340ms instead of 2100ms in the current package version. ACS still seems to be a little faster, but it is 250ms compared to 340ms, so much better parity.

Working on getting it cleaned up and merged in.

**Comment by rfx77** [comment] 2021-02-16 15:58
Thank you for that. I will give it a try when i have time.

**Comment by markdirish** [comment] 2021-08-03 18:05
Should be live in new version 2.4.0

**Closed by markdirish** 2021-08-03 18:05 UTC
