### ISSUE TITLE
CLOB support

### ISSUE THREAD

**Issue by worksofliam** [markdirish/node-odbc#129] opened 2020-10-05 14:30 UTC
According to this comment, CLOB is not yet supported - https://github.com/markdirish/node-odbc/issues/11#issuecomment-504989633

Is this still the case?

E.g. if I define a stored procedure like so, I am unable to pass in character data?

```
create or replace procedure WEBORDER.theprocedure (IN a clob(10k), OUT b clob(32k), OUT c char(259)) LANGUAGE RPGLE EXTERNAL NAME WEBORDER.MYPROGRAM GENERAL;
```

```
const myinputclob = `my huge string yo`
const results = await db2.callProcedure(SCHEMA, 'theprocedure', [myinputclob, undefined, undefined]);
```

Thanks!

**Comment by markdirish** [comment] 2020-10-20 19:41
The problem is the IBM i Access driver, which has an allowlist of SQL Types that it allows SQLBindParameter to bind to. And CLOB ain't on it!

The driver itself is closed source, but I added CLOB to the white list and was able to bind IN-INOUT-OUT for both character strings and binary data. I'm not sure where else this white list is used, so it will take more looking. But since this isn't a Node.js `odbc` issue, I'm closing.

**Closed by markdirish** 2020-10-20 19:41 UTC
