### ISSUE TITLE
Error getting information about maximum column length from the connection

### ISSUE THREAD

**Issue by duffett** [markdirish/node-odbc#128] opened 2020-10-05 13:34 UTC
Using UnixODBC to connect to a MS Access (mdb) database via DSN.  Application works in Windows but when deployed on Linux receive the following error when calling odbc.connect or odbc.pool.  

`Error getting information about maximum column length from the connection`

Successfully able to connect and query database via isql -v "DNS_NAME"

```
[ODBC][700][1601652777.297816][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x31a1150
[ODBC][700][1601652777.297871][SQLSetEnvAttr.c][189]
                Entry:
                        Environment = 0x31a1150
                        Attribute = SQL_ATTR_ODBC_VERSION
                        Value = 0x3
                        StrLen = -5
[ODBC][700][1601652777.297897][SQLSetEnvAttr.c][363]
                Exit:[SQL_SUCCESS]
[ODBC][700][1601652777.648390][SQLAllocHandle.c][375]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x31a1150
[ODBC][700][1601652777.648448][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x7fe9480008c0
[ODBC][700][1601652777.648504][SQLDriverConnect.c][726]
                Entry:
                        Connection = 0x7fe9480008c0
                        Window Hdl = (nil)
                        Str In = [DSN=LtArm][length = 9 (SQL_NTS)]
                        Str Out = 0x7fe95a158e20
                        Str Out Max = 2048
                        Str Out Ptr = (nil)
                        Completion = 0
                UNICODE Using encoding ASCII 'ISO8859-1' and UNICODE 'UCS-2LE'

[ODBC][700][1601652777.650846][SQLDriverConnect.c][1582]
                Exit:[SQL_SUCCESS]
                        Connection Out [[][length = 0 (SQL_NTS)]]
[ODBC][700][1601652777.650881][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x7fe9480008c0
                        Info Type = SQL_MAX_COLUMN_NAME_LEN (30)
                        Info Value = 0x3185b48
                        Buffer Length = 2
                        StrLen = (nil)
[ODBC][700][1601652777.650905][SQLGetInfo.c][617]
                Exit:[SQL_ERROR]
[ODBC][700][1601652777.650935][SQLGetDiagField.c][895]
                Entry:
                        Connection = 0x7fe9480008c0
                        Rec Number = 0
                        Diag Ident = 2
                        Diag Info Ptr = 0x7fe95a159600
                        Buffer Length = -6
                        String Len Ptr = (nil)
[ODBC][700][1601652777.650958][SQLGetDiagField.c][915]
                Exit:[SQL_SUCCESS]
````

**Comment by Renari** [comment] 2020-12-08 18:44
Same issue here.

**Comment by markdirish** [comment] 2021-02-25 16:45
@duffett and @Renari , let's see if we can get this solved.

It seems clear that the issue is here: https://github.com/markdirish/node-odbc/blob/480d25af7014bc26f7569e9e6c9a4efecedc41ac/src/odbc.cpp#L368-L380

The error object returns a message of `Error getting information about maximum column length from the connection`, but it should also have something on the `odbcErrors` property of the error object. If you print the whole error object, it should show them. This will display the information that the driver or driver manager returned about the error, that will be more helpful in determining the error.

It's possible that the driver simply doesn't implement that option for SQLGetInfo, although in that case I would expect it to return 0 instead of erroring. It isn't vital that the information is returned, so maybe I can fail silently and use a "best guess" value if I can't get the true max column length.

**Comment by vognev** [comment] 2021-04-20 11:48
in my case mdbtools odbc driver just does not supports SQL_MAX_COLUMN_NAME_LEN -  https://github.com/mdbtools/mdbtools/blob/dev/src/odbc/odbc.c#L1911, maybe it is possible to make an option/workaround for it?

**Comment by markdirish** [comment] 2021-05-10 16:10
Ready to publish when 2.4.0 gets released

**Comment by markdirish** [comment] 2021-07-06 19:15
2.4.0 is now published and this should be fixed. Feel free to open if it still seems broken!

**Closed by markdirish** 2021-07-06 19:15 UTC
Labels: ready to publish
