### ISSUE TITLE
Process crashes while connecting to Database on Node v11.15.0

### ISSUE THREAD

**Issue by JTBS** [markdirish/node-odbc#7] opened 2019-06-11 19:39 UTC
Hi,
All worked fine on Windows with Node version v10.14.2.
I did fresh install of **Node v11.15.0** on Linux box and tested project.

When I try to open DB connection, process exists with below failure:
**error Command failed with signal "SIGSEGV".**

Is it possible it is specific to Node version I am using.
Anyone tested 2.0 with above exact version or seeing similar issues?

**Comment by JTBS** [comment] 2019-06-11 20:01
Quick update:
I tested again on Linux with different Node versions.

It works well with 8.16.0 and performance improvement is almost 50% [at least for my scenario]
**But I could not get it working on 10.x or 11.x on Linux.**
Either error or crash in these versions - at least for me.

**Comment by markdirish** [comment] 2019-06-11 20:07
I run mine on Linux (RHEL) at Node v 10.16. On your fresh Linux boxes do you have all your unixODBC stuff set up (drivers in `odbcinst.ini`, DSNs in `odbc.ini`)?

**Comment by JTBS** [comment] 2019-06-11 21:34
Yes. On linux box, I have ODBC is installed and I use MS SQL ODBC driver version 13:
/libmsodbcsql-13.1.so.6.0

I can use version 17 which is more latest if that helps.
But with older Node version it worked fine even with 13 - so did not bother.

**I have quick question:** We are bit pressed to improve performance and certainly new version is much better mainly for large data. Do you know of any quick workaround or API in older version 1.4.6 that we can tweak to just get performance improvement part - while we wait for 2.0 to stabilize for production use - as we need to complete more testing on 2.0?

**Comment by markdirish** [comment] 2019-06-12 01:39
I tried with Windows 10, Node.js 12.4.0, and using the MS SQL ODBC driver version 13. Seemed to work find in that case. I will keep trying different configurations and see if I can recreate the SIGSEGV. Is there any other information it gives? (Usually not with a segfault, but though I'd try).

As for your question, the answer is unfortunately no. 2.0 began as a rewrite of how data is retrieved to improve performance, migrating from using SQLGetData to SQLBindColumns. Unfortunately this is an involved process, and not something where you can just change a few dozen lines, more like a few hundred. Another improvement may have come from switching from NAN to N-API as API for building Node.js addons in C/C++. N-API is ABI stable, meaning you should be able to take your `odbc.node` file in the `build/` directory as compiled in Node.js 8 and use it in Node.js 10, 11, 12, etc. Again, the switch from NAN to N-API requires you to alter hundreds of lines of code.

The only v1.x improvement I could think of would be to take out the SimpleQueue class from the JavaScript library portion. I think this class exists to slow down queries so they don't hammer the database, so removing it (and rewriting the code in the Database class) _might_ make things noticeably faster. It also might break the whole package!

**Comment by JTBS** [comment] 2019-06-12 17:35
Thank you. appreciate getting back on this. As of now I am able to set to 8.16.0 node version and get things going. Will retest higher versions once we have stable runs in 8.16.0 as needed.

**Comment by erayd** [comment] 2019-08-06 09:52
I'm experiencing the same issue.

@markdirish - I have a minimal-case docker config that can replicate this against SQL Server 2016. Would it be useful to you if I posted that somewhere?

**Comment by markdirish** [comment] 2019-08-06 12:30
@erayd 

Yeah, I still haven't been able to replicate this, so a docker config would be helpful in tracking it down. Thanks!

**Comment by erayd** [comment] 2019-08-06 13:54
@markdirish 

Here you go - minimal test case. To replicate against SQL Server 2016:

1. Edit the database definition in `etc/odbc.ini` to point to a real database
2. Edit the username and password in `app/main.js` to be a real account
3. `make container`
4. `make run`

If you want to investigate inside the container, I've also added a `make shell` target for you.

[segfault-demo.tar.gz](https://github.com/markdirish/node-odbc/files/3472574/segfault-demo.tar.gz)

Please let me know if there's anything I can try on my end that would be useful.

**Comment by rcbyrne** [comment] 2019-08-29 21:08
I also cannot get this working on Node 10 but have it working fine with Node 8

I am using ODBC Driver 13 & Node 10.16.3

I am getting a different error "Segmentation fault (core dumped)". Is there a way I could get a deeper insight into what is actually failing?

**Comment by markdirish** [comment] 2019-08-30 00:55
You can build with 'DEBUG' in the defines, and it should show the last thing that happened before the segfault which can be helpful. I've noticed a few SEGFAULTs when running this package as well, mostly dealing with closing connections during pooling.

I'm hoping to push out v 2.2.0 sometime next week to make the package more stable.

**Comment by maingi4** [comment] 2019-11-27 14:46
Hey @markdirish,

Thanks for the great Lib. I had been using this for quite a while without issues running on node 8.x on both windows (development) and docker in Linux for quite a while.

We recently upgraded to `nodeJS 12.3` and I used your `2.2.2` release which is the latest right now. In windows the library runs just fine no matter what query I throw at it, however in Linux (docker) .. it throws the SEGFAULT (`SIGSEGV`) while executing some queries only.

Steps to reproduce:
1. Use Connection and not Pool
2. `query` the statement given below
3. the error throws at line#71 in `Connection.js` which reads something like `return this.odbcConnection.query(sq....`

The query:

```
select a.tbcreator as \"schema\", a.tbcreator as \"database\", a.tbname as table_name, b.type as table_type, a.name as column_name, a.default as column_default, a.coltype as type_name, a.length as character_maximum_length, a.scale as decimal_digits, a.nulls as is_nullable, a.colno as ordinal_position from sysibm.syscolumns a inner join sysibm.systables b on a.tbname = b.name where b.type in ('T', 'V') and a.tbcreator not in ('SYSIBM', 'SYSCAT', 'SYSSTAT', 'SYSIBMADM', 'SYSTOOLS') and b.creator not in ('SYSIBM', 'SYSCAT', 'SYSSTAT', 'SYSIBMADM', 'SYSTOOLS', 'SYSPUBLIC') limit 1
```

Note that a simple query select blah from table seems to work just fine.

The above stated query also works just fine on my windows laptop running windows 10.

The docker container's root image is `node:12.13.0`, I do add a lot of stuff on top though.

**Comment by maingi4** [comment] 2019-11-27 15:25
@markdirish after some more digging.. the fault seems to arise at this statement at `line#720` in `odbc_connection.cpp` c++ file:

```
data->sqlReturnCode = odbcConnectionObject->RetrieveResultSet(data);
```

`P.S.` Digging = adding lots of print statements :)

**Comment by markdirish** [comment] 2022-04-19 00:28
I've squashed a lot of process crashes in the last few years, and I am going to assume that this issue has been fixed as part of that (since I haven't received similar issues recently). Also, since Node 8 and 10 are out of support, and 12 will soon be (this month), I'm hoping the issue no longer persists in Node 14+

**Closed by markdirish** 2022-04-19 00:28 UTC
