### ISSUE TITLE
[BUG] Unhandled Promise Rejection When Pool Connections Fail

### ISSUE THREAD

**Issue by DavidRusso** [markdirish/node-odbc#176] opened 2021-04-06 22:06 UTC
In v2.4.0-beta.1, the pool constructor fails due to an unhandled promise rejection when connections fail. Such as for non-existent DSN, incorrect uid/pwd, or whatever.

For example:

```
const odbc = require("odbc");

(async () => {
  try {
    const pool = await odbc.pool("DSN=DOES_NOT_EXIST;");
    await pool.close();
  }
  catch (error) {
    console.error("caught");
    console.error(error);
  }
})();
```

I would expect the `catch` block to execute, but instead an UnhandledPromiseRejection message is output. The result is similar if a callback is used -- the UnhandledPromiseRejection message is output and the callback is not invoked.

This makes it impossible to handle common errors.

The problem does not occur in version 2.3.6.

**Comment by markdirish** [comment] 2021-04-20 01:06
Found and fixes in #180 . Problem was the new use of `Promise.race`, which I wasn't wrapping in a try/catch, and therefore not handling the error with a `reject(error)`. Now running the code above I get a nice error:
```
[Error: [odbc] Error connecting to the database] {
  odbcErrors: [
    {
      state: 'IM002',
      code: 0,
      message: '[unixODBC][Driver Manager]Data source name not found and no default driver specified'
    }
  ]
}

```

**Comment by DavidRusso** [comment] 2021-06-02 15:57
This doesn't seem to be working correctly for me in 2.4.0-beta.2. 

Now, my original example above doesn't produce any output of any kind. There is no more unhandled promise rejection warning, but still the catch block doesn't execute.

I tried modifying the example like this:

```
const odbc = require("odbc");

(async () => {
  try {
    const pool = await odbc.pool("DSN=DOES_NOT_EXIST;");
    console.log("pool created");
    const connection = await pool.connect();
    console.log("connection created.");
    await pool.close();
  }
  catch (error) {
    console.error("caught");
    console.error(error);
  }
})();
```

It just outputs "pool created" and the process ends.

I've tested on both Windows and IBM i, the result is the same.

**Comment by markdirish** [comment] 2021-06-23 14:12
Yeah this one will take some thinking...

The issue is here: 
https://github.com/markdirish/node-odbc/blob/c011dc0e29b984863711c49a0e77933cfc3096e6/lib/Pool.js#L48-L53

Basically, connections are created in the background and then are made available to the user as they become available. They are made X at a time, where X is whatever the user passes as `maxActivelyConnecting` to the config object. Because these connections are made in the background, I have to try to think how to allow the user to catch the errors that are generated in the background... or just throw them globally and have the program crash.

Perhaps I can make `init` wait until at least one connection is returned, propagate up to `.pool`, and then throw the error from there so the user has access to handle the error...

The issue is any connection errors that occur that happen for reasons that aren't malformed connection strings won't really be available to the user to handle, but I think that was always the case when connections are made in the background.

Taking a look at this today.

**Comment by markdirish** [comment] 2021-07-06 19:00
2.4.0 is now published and this should be fixed. Feel free to open if it still seems broken!

**Closed by markdirish** 2021-07-06 19:00 UTC
Labels: ready to publish
